// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSAFinalProject.Models;

namespace WSAFinalProject.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20211205205034_Moviedb")]
    partial class Moviedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WSAFinalProject.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "RomCom"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "SuperHero"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Musical"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("WSAFinalProject.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "A rescue crew investigates a spaceship that disappeared into a black hole and has now returned...with someone or something new on-board.",
                            Duration = 96,
                            GenreId = 2,
                            Name = "Event Horizon",
                            Year = 1997
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
                            Duration = 127,
                            GenreId = 2,
                            Name = "Jurassic Park",
                            Year = 1993
                        },
                        new
                        {
                            MovieId = 3,
                            Description = "Frank Abagnale, Jr. (Leonardo DiCaprio) worked as a doctor, a lawyer, and as a co-pilot for a major airline -- all before his 18th birthday. A master of deception, he was also a brilliant forger, whose skill gave him his first real claim to fame: At the age of 17, Frank Abagnale, Jr. became the most successful bank robber in the history of the U.S. FBI Agent Carl Hanratty (Tom Hanks) makes it his prime mission to capture Frank and bring him to justice, but Frank is always one step ahead of him.",
                            Duration = 141,
                            GenreId = 6,
                            Name = "Catch me if you can",
                            Year = 2002
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "South Boston cop Billy Costigan (Leonardo DiCaprio) goes under cover to infiltrate the organization of gangland chief Frank Costello (Jack Nicholson). As Billy gains the mobster's trust, a career criminal named Colin Sullivan (Matt Damon) infiltrates the police department and reports on its activities to his syndicate bosses. When both organizations learn they have a mole in their midst, Billy and Colin must figure out each other's identities to save their own lives.",
                            Duration = 151,
                            GenreId = 6,
                            Name = "The Departed",
                            Year = 2006
                        },
                        new
                        {
                            MovieId = 5,
                            Description = "Captain John Miller (Tom Hanks) takes his men behind enemy lines to find Private James Ryan, whose three brothers have been killed in combat. Surrounded by the brutal realties of war, while searching for Ryan, each man embarks upon a personal journey and discovers their own strength to triumph over an uncertain future with honor, decency and courage.",
                            Duration = 169,
                            GenreId = 6,
                            Name = "Saving Private Ryan",
                            Year = 1998
                        },
                        new
                        {
                            MovieId = 6,
                            Description = "On the way to a tryout with the Chicago Cubs, young baseball phenom Roy Hobbs (Robert Redford) is shot by the unstable Harriet Bird (Barbara Hershey). After 16 years, Hobbs returns to pro baseball as a rookie for the last-place New York Knights. Despite early arguments with his manager, Pop Fisher (Wilford Brimley), Hobbs becomes one of the best players in the league, and the Knights start winning. But this upsets the Judge (Robert Prosky), their owner, who wants Hobbs to lose games, not win.",
                            Duration = 144,
                            GenreId = 3,
                            Name = "The Natural",
                            Year = 1984
                        },
                        new
                        {
                            MovieId = 7,
                            Description = "The culmination of nearly 10 years' work and conclusion to Peter Jackson's epic trilogy based on the timeless J.R.R. Tolkien classic, The Lord of the Rings: The Return of the King presents the final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Hobbits Frodo and Sam reach Mordor in their quest to destroy the `one ring', while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
                            Duration = 263,
                            GenreId = 6,
                            Name = "Lord of the Rings: Return of the King Extended Edition",
                            Year = 2003
                        },
                        new
                        {
                            MovieId = 8,
                            Description = "In the 14th century, the harmony that humans, animals and gods have enjoyed begins to crumble. The protagonist, young Ashitaka - infected by an animal attack, seeks a cure from the deer-like god Shishigami. In his travels, he sees humans ravaging the earth, bringing down the wrath of wolf god Moro and his human companion Princess Mononoke. Hiskattempts to broker peace between her and the humans brings only conflict.",
                            Duration = 133,
                            GenreId = 6,
                            Name = "Princess Mononoke",
                            Year = 1997
                        },
                        new
                        {
                            MovieId = 9,
                            Description = "A teenage hacker finds himself framed for the theft of millions of dollars from a major corporation. Master hacker Dade Murphy, aka Zero Cool, aka Crash Override, has been banned from touching a keyboard for seven years after crashing over 1,500 Wall Street computers at the age of 11. Now keen to get back in front of a monitor, he finds himself in more trouble than ever.",
                            Duration = 107,
                            GenreId = 6,
                            Name = "Hackers",
                            Year = 1995
                        },
                        new
                        {
                            MovieId = 10,
                            Description = "This acclaimed biographical drama presents major events in the life of Mohandas Gandhi (Ben Kingsley), the beloved Indian leader who stood against British rule over his country. Dedicated to the concept of nonviolent resistance, Gandhi is initially dismissed by English officials, including the influential Lord Irwin (John Gielgud), but eventually he and his cause become internationally renowned, and his gatherings of passive protest move India towards independence.",
                            Duration = 191,
                            GenreId = 3,
                            Name = "Gandhi",
                            Year = 1982
                        });
                });

            modelBuilder.Entity("WSAFinalProject.Models.Movie", b =>
                {
                    b.HasOne("WSAFinalProject.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
